title: #Your awesome title
author: Shad6owh4rd
email: #your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just started using GitHub.

# social links
github_username: Shad6owh4rd # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
